# Generated by Django 5.2.7 on 2025-11-14 22:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexpage', '0002_alter_flexpage_body'),
        ('images', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the page for organizational purposes.', max_length=100),
        ),
        migrations.CreateModel(
            name='ResourcesIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('body', wagtail.fields.StreamField([('six', 0), ('text', 1), ('richtext', 2), ('image', 3), ('call_to_action_1', 11), ('faq', 12)], blank=True, block_lookup={0: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.RichTextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'The main CTA text content', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page for the button to link to', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text (defaults to page title if empty)', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional: Make the entire CTA clickable by selecting a target page', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image for the CTA', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], 'help_text': 'How to display the image', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], 'help_text': 'Style for left/right images (not used for background)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6), ('target_url', 7), ('image', 8), ('image_layout', 9), ('image_style', 10)]], {}), 12: ('blocks.blocks.FaqListBlock', (), {})}, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
