# Generated by Django 5.2.9 on 2025-12-17 23:54

from django.db import migrations
import json


def migrate_flexpage_to_layout_sections(apps, schema_editor):
    """
    Migrate existing FlexPage body content to use LayoutSectionBlock.
    Wraps existing content in a layout_section block.
    For pages under ResourcesIndex, use sidebar layout with resources nav enabled.
    For all other pages, use full_width layout.
    """
    import uuid
    from django.db import connection

    FlexPage = apps.get_model('flexpage', 'FlexPage')
    ResourcesIndex = apps.get_model('flexpage', 'ResourcesIndex')

    # Work directly with the database to access the raw JSON
    with connection.cursor() as cursor:
        # Get all FlexPage records
        cursor.execute("SELECT page_ptr_id, body FROM flexpage_flexpage")
        pages_data = cursor.fetchall()

        for page_id, body_json in pages_data:
            # Parse existing body content
            try:
                existing_body = json.loads(body_json) if body_json else []
            except (json.JSONDecodeError, TypeError, ValueError):
                existing_body = []

            # Skip if body is already empty
            if not existing_body:
                cursor.execute("UPDATE flexpage_flexpage SET body = %s WHERE page_ptr_id = %s",
                             [json.dumps([]), page_id])
                continue

            # Get the page object to check ancestry
            try:
                page = FlexPage.objects.get(id=page_id)
                # Check if this page is under a ResourcesIndex
                is_under_resources = False
                ancestors = page.get_ancestors()
                for ancestor in ancestors:
                    if ancestor.specific_class == ResourcesIndex:
                        is_under_resources = True
                        break
            except Exception:
                is_under_resources = False

            # Determine layout based on page location
            if is_under_resources:
                layout = 'sidebar'
                show_resources_nav = True
            else:
                layout = 'full_width'
                show_resources_nav = False

            # Wrap existing content in a layout_section block
            new_body = [
                {
                    'type': 'layout_section',
                    'value': {
                        'layout': layout,
                        'content': existing_body,
                        'sidebar': [],
                        'show_resources_nav': show_resources_nav
                    },
                    'id': str(uuid.uuid4())
                }
            ]

            # Update the page in database
            cursor.execute("UPDATE flexpage_flexpage SET body = %s WHERE page_ptr_id = %s",
                         [json.dumps(new_body), page_id])


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by unwrapping layout_section blocks.
    Extracts content from layout_section and restores it to the body.
    """
    from django.db import connection

    # Work directly with the database to access the raw JSON
    with connection.cursor() as cursor:
        # Get all FlexPage records
        cursor.execute("SELECT page_ptr_id, body FROM flexpage_flexpage")
        pages_data = cursor.fetchall()

        for page_id, body_json in pages_data:
            try:
                current_body = json.loads(body_json) if body_json else []
            except (json.JSONDecodeError, TypeError):
                current_body = []

            # Skip if body is empty
            if not current_body:
                continue

            # Extract content from all layout_section blocks
            old_body = []
            for block in current_body:
                if block.get('type') == 'layout_section':
                    # Extract the content field from the layout_section
                    content = block.get('value', {}).get('content', [])
                    old_body.extend(content)
                else:
                    # Keep non-layout_section blocks as-is
                    old_body.append(block)

            # Update the page in database
            cursor.execute("UPDATE flexpage_flexpage SET body = %s WHERE page_ptr_id = %s",
                         [json.dumps(old_body), page_id])


class Migration(migrations.Migration):

    dependencies = [
        ('flexpage', '0005_alter_flexpage_body'),
    ]

    operations = [
        migrations.RunPython(
            migrate_flexpage_to_layout_sections,
            reverse_migration
        ),
    ]
