# Generated by Django 5.2.9 on 2026-02-10 01:57

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('title', models.CharField(help_text='The event title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle or tagline', max_length=255)),
                ('event_type', models.CharField(choices=[('registration', 'Registration'), ('referee_training', 'Referee Training'), ('coach_certification', 'Coach Certification'), ('training_camp', 'Training Camp'), ('special_event', 'Special Event'), ('other', 'Other')], default='other', help_text='Type of event', max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the event')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date (leave blank for single-day events)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('waitlist', 'Waitlist'), ('closed', 'Closed')], default='pending', help_text='Current status of the event', max_length=20)),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1), ('call_to_action_1', 9)], blank=True, block_lookup={0: ('blocks.blocks.RichTextBlock', (), {}), 1: ('blocks.blocks.ImageBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'The main CTA text content', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page for the button to link to', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text (defaults to page title if empty)', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional: Make the entire CTA clickable by selecting a target page', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image for the CTA', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], 'help_text': 'How to display the image', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], 'help_text': 'Style for left/right images (not used for background)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 2), ('page', 3), ('button_text', 4), ('target_url', 5), ('image', 6), ('image_layout', 7), ('image_style', 8)]], {})}, null=True)),
                ('link', models.URLField(blank=True, help_text='External link (e.g., registration portal URL)')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('program', models.ForeignKey(blank=True, help_text='Optional: associate this event with a specific program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='programs.program')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_date', 'title'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
    ]
