# Generated by Django 6.0.2 on 2026-02-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_end',
            field=models.DateField(blank=True, help_text='Optional: when registration closes', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_start',
            field=models.DateField(blank=True, help_text='Optional: when registration opens', null=True),
        ),
    ]
