# Generated by Django 6.0.2 on 2026-03-06 00:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('image', 2), ('doc', 3), ('page', 4), ('cta_text', 9), ('cta_snippet', 12), ('recent_news', 17)], blank=True, block_lookup={0: ('blocks.blocks.RichTextBlock', (), {}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 2: ('blocks.blocks.ImageBlock', (), {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 4: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 7: ('wagtail.blocks.PageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('headline', 5), ('text', 6), ('page', 7), ('button_text', 8)]], {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('cta.CTA',), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Select one or more CTAs. A random live one will be displayed each page load.', 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('ctas', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 14), ('num_items', 15), ('filter_by_tag', 16)]], {})}, null=True),
        ),
    ]
