# Generated by Django 5.1.8 on 2025-04-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsitem_body_newsitemtags_newsitem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='body',
        ),
    ]
