# Generated by Django 5.1.8 on 2025-04-14 21:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsitem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('carousel', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('author', 0)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 2)]], {'max_num': 5, 'min_num': 1})}, null=True),
        ),
    ]
