# Generated by Django 5.1.8 on 2025-04-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_author_expire_at_author_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.author'),
        ),
    ]
