# Generated by Django 5.1.8 on 2025-04-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_author_locked_author_locked_at_author_locked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_edit_author_name', 'Can edit author name')]},
        ),
    ]
