# Generated by Django 5.1.8 on 2025-04-16 20:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
