# Generated by Django 5.1.8 on 2025-04-17 14:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newsitem_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('faq', 1), ('text', 2), ('carousel', 6), ('image', 7), ('doc', 8), ('page', 9), ('author', 10), ('call_to_action_1', 14)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.FaqListBlock', (), {}), 2: ('blocks.blocks.TextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 4), ('author', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('image', 3), ('quotation', 5)]], {}), 7: ('blocks.blocks.ImageBlock', (), {}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 9: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('news.Author',), {}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 11), ('page', 12), ('button_text', 13)]], {})}, null=True),
        ),
    ]
