# Generated by Django 5.1.8 on 2025-04-17 19:09

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_author_locale_author_translation_key'),
    ]

    operations = [
        BootstrapTranslatableModel('news.Author')
        # BootstrapTranslatableModel('anotherapp.SomeModel')
    ]
