# Generated by Django 5.2.9 on 2025-12-19 21:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_newsitem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('carousel', 4), ('image', 5), ('doc', 6), ('page', 7), ('author', 8), ('hero', 13), ('recent_news', 18)], blank=True, block_lookup={0: ('blocks.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('text', 2), ('author', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('image', 1), ('quotation', 3)]], {}), 5: ('blocks.blocks.ImageBlock', (), {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 7: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('news.Author',), {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 11: ('wagtail.blocks.PageChooserBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('headline', 9), ('text', 10), ('page', 11), ('button_text', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 15), ('num_items', 16), ('filter_by_tag', 17)]], {})}, null=True),
        ),
    ]
