# Generated by Django 5.2.9 on 2025-12-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_alter_author_options_remove_newsitem_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
