# Generated by Django 5.2.9 on 2025-12-24 20:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 1), ('doc', 2), ('page', 3), ('cta_text', 8), ('recent_news', 13)], blank=True, block_lookup={0: ('blocks.blocks.RichTextBlock', (), {}), 1: ('blocks.blocks.ImageBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone Blocks'}), 3: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 6: ('wagtail.blocks.PageChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('headline', 4), ('text', 5), ('page', 6), ('button_text', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 11: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('subtitle', 10), ('num_items', 11), ('filter_by_tag', 12)]], {})}, null=True),
        ),
    ]
