# Generated by Django 5.2.9 on 2025-12-24 20:37

from django.db import migrations
import json


def rename_hero_block_to_cta_text(apps, schema_editor):
    """
    Rename 'hero' block type to 'cta_text' in NewsItem body StreamField.
    """
    NewsItem = apps.get_model('news', 'NewsItem')

    for page in NewsItem.objects.all():
        if page.body:
            # Parse the StreamField JSON data
            try:
                body_data = json.loads(page.body.raw_text) if hasattr(page.body, 'raw_text') else page.body

                # If it's already a list, use it directly
                if isinstance(body_data, list):
                    stream_data = body_data
                else:
                    # Otherwise try to get it from the StreamField
                    stream_data = json.loads(page.body)

                # Flag to track if we made changes
                modified = False

                # Update block types from 'hero' to 'cta_text'
                for block in stream_data:
                    if block.get('type') == 'hero':
                        block['type'] = 'cta_text'
                        modified = True

                # Save if we made changes
                if modified:
                    page.body = json.dumps(stream_data)
                    page.save(update_fields=['body'])

            except (json.JSONDecodeError, AttributeError, TypeError) as e:
                # Skip pages with invalid or empty body data
                print(f"Skipping NewsItem {page.id}: {e}")
                continue


def reverse_rename_hero_block(apps, schema_editor):
    """
    Reverse migration: rename 'cta_text' back to 'hero'.
    """
    NewsItem = apps.get_model('news', 'NewsItem')

    for page in NewsItem.objects.all():
        if page.body:
            try:
                body_data = json.loads(page.body.raw_text) if hasattr(page.body, 'raw_text') else page.body

                if isinstance(body_data, list):
                    stream_data = body_data
                else:
                    stream_data = json.loads(page.body)

                modified = False

                for block in stream_data:
                    if block.get('type') == 'cta_text':
                        block['type'] = 'hero'
                        modified = True

                if modified:
                    page.body = json.dumps(stream_data)
                    page.save(update_fields=['body'])

            except (json.JSONDecodeError, AttributeError, TypeError) as e:
                print(f"Skipping NewsItem {page.id}: {e}")
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_alter_newsitem_body'),
    ]

    operations = [
        migrations.RunPython(rename_hero_block_to_cta_text, reverse_rename_hero_block),
    ]
