# Generated by Django 5.2.9 on 2026-01-07 01:21

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('title', models.CharField(help_text='The hero title', max_length=255)),
                ('text', wagtail.fields.RichTextField(help_text='The main hero text content')),
                ('button_text', models.CharField(blank=True, help_text='Button text', max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, help_text='Button URL', null=True)),
                ('image_layout', models.CharField(choices=[('background', 'Background - Image fills entire hero as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], default='background', help_text='How to display the image', max_length=20)),
                ('image_style', models.CharField(choices=[('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], default='fill', help_text='Style for left/right images (not used for background)', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('cta_text', 4), ('six_philosophies', 5), ('programs', 8), ('text', 9), ('rich_text', 10), ('image', 11), ('page', 12), ('recent_news', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our Programs', 'help_text': 'Main heading for this programs section', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7)]], {}), 9: ('blocks.blocks.TextBlock', (), {}), 10: ('blocks.blocks.RichTextBlock', (), {}), 11: ('blocks.blocks.ImageBlock', (), {}), 12: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 7), ('num_items', 14), ('filter_by_tag', 15)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
