# Generated by Django 5.2.9 on 2026-02-10 01:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('cta_text', 4), ('six_philosophies', 5), ('programs', 8), ('text', 9), ('rich_text', 10), ('image', 11), ('page', 12), ('recent_news', 16), ('upcoming_events', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our Programs', 'help_text': 'Main heading for this programs section', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7)]], {}), 9: ('blocks.blocks.TextBlock', (), {}), 10: ('blocks.blocks.RichTextBlock', (), {}), 11: ('blocks.blocks.ImageBlock', (), {}), 12: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 7), ('num_items', 14), ('filter_by_tag', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Upcoming Events', 'help_text': 'Main heading for this events section', 'max_length': 100, 'required': True}), 18: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Maximum number of events to display', 'max_value': 20, 'min_value': 1, 'required': True}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'All Types'), ('registration', 'Registration'), ('referee_training', 'Referee Training'), ('coach_certification', 'Coach Certification'), ('training_camp', 'Training Camp'), ('special_event', 'Special Event'), ('other', 'Other')], 'help_text': 'Optional: show only events of this type', 'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'All Statuses'), ('pending', 'Pending'), ('active', 'Active'), ('waitlist', 'Waitlist'), ('closed', 'Closed')], 'help_text': 'Optional: show only events with this status', 'required': False}), 21: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Include events whose start date has passed', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 17), ('subtitle', 7), ('num_items', 18), ('filter_by_type', 19), ('filter_by_status', 20), ('show_past_events', 21)]], {})}, null=True),
        ),
    ]
