# Generated by Django 5.2.7 on 2025-10-27 03:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {})}, null=True),
        ),
    ]
