# Generated by Django 5.2.7 on 2025-10-27 21:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
