# Generated by Django 5.2.7 on 2025-10-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_cta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='CTA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_cta', to='home.cta'),
        ),
    ]
