# Generated by Django 5.2.7 on 2025-10-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_homepage_cta_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
