# Generated by Django 5.2.7 on 2025-10-27 23:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('faq', 5), ('text', 6), ('carousel', 10), ('image', 11), ('page', 12), ('recent_news', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.FaqListBlock', (), {}), 6: ('blocks.blocks.TextBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('image', 7), ('quotation', 9)]], {}), 11: ('blocks.blocks.ImageBlock', (), {}), 12: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 14), ('num_items', 15), ('filter_by_tag', 16)]], {})}, null=True),
        ),
    ]
