# Generated by Django 5.2.7 on 2025-10-29 18:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('six_philosophies', 5), ('faq', 6), ('text', 7), ('carousel', 11), ('image', 12), ('page', 13), ('recent_news', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('blocks.blocks.FaqListBlock', (), {}), 7: ('blocks.blocks.TextBlock', (), {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.TextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('text', 9), ('author', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('image', 8), ('quotation', 10)]], {}), 12: ('blocks.blocks.ImageBlock', (), {}), 13: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('subtitle', 15), ('num_items', 16), ('filter_by_tag', 17)]], {})}, null=True),
        ),
    ]
