# Generated by Django 5.2.7 on 2025-11-05 23:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('six_philosophies', 5), ('programs', 8), ('faq', 9), ('text', 10), ('carousel', 14), ('image', 15), ('page', 16), ('recent_news', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our Programs', 'help_text': 'Main heading for this programs section', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7)]], {}), 9: ('blocks.blocks.FaqListBlock', (), {}), 10: ('blocks.blocks.TextBlock', (), {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('text', 12), ('author', 12)]], {}), 14: ('wagtail.blocks.StreamBlock', [[('image', 11), ('quotation', 13)]], {}), 15: ('blocks.blocks.ImageBlock', (), {}), 16: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 18: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('subtitle', 7), ('num_items', 18), ('filter_by_tag', 19)]], {})}, null=True),
        ),
    ]
