# Generated by Django 5.2.7 on 2025-11-11 23:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_body'),
        ('images', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional image for the CTA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='cta',
            name='image_layout',
            field=models.CharField(choices=[('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], default='background', help_text='How to display the image', max_length=20),
        ),
        migrations.AddField(
            model_name='cta',
            name='image_style',
            field=models.CharField(choices=[('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], default='fill', help_text='Style for left/right images (not used for background)', max_length=20),
        ),
        migrations.AddField(
            model_name='cta',
            name='target_url',
            field=models.ForeignKey(blank=True, help_text='Optional: Make the entire CTA clickable by selecting a target page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='cta',
            name='button_text',
            field=models.CharField(help_text='Button text', max_length=100),
        ),
        migrations.AlterField(
            model_name='cta',
            name='button_url',
            field=models.URLField(help_text='Button URL'),
        ),
        migrations.AlterField(
            model_name='cta',
            name='text',
            field=wagtail.fields.RichTextField(help_text='The main CTA text content'),
        ),
        migrations.AlterField(
            model_name='cta',
            name='title',
            field=models.CharField(help_text='The CTA title', max_length=255),
        ),
    ]
