# Generated by Django 5.2.7 on 2025-11-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_cta_image_cta_image_layout_cta_image_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='button_text',
            field=models.CharField(blank=True, help_text='Button text', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cta',
            name='button_url',
            field=models.URLField(blank=True, help_text='Button URL', null=True),
        ),
    ]
