# Generated by Django 5.2.9 on 2025-12-19 21:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('six_philosophies', 5), ('programs', 8), ('text', 9), ('image', 10), ('page', 11), ('recent_news', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our Programs', 'help_text': 'Main heading for this programs section', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7)]], {}), 9: ('blocks.blocks.TextBlock', (), {}), 10: ('blocks.blocks.ImageBlock', (), {}), 11: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 13: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 7), ('num_items', 13), ('filter_by_tag', 14)]], {})}, null=True),
        ),
    ]
