# Generated by Django 5.2.9 on 2025-12-23 23:41

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models


def copy_cta_data_back(apps, schema_editor):
    """
    Copy CTA data from site_settings back to home
    """
    db_alias = schema_editor.connection.alias

    # Use raw SQL to copy data from site_settings_cta to home_cta
    with schema_editor.connection.cursor() as cursor:
        # Copy all data from site_settings_cta to home_cta
        cursor.execute("""
            INSERT INTO home_cta (
                id, translation_key, locale_id, live, has_unpublished_changes,
                first_published_at, last_published_at, go_live_at, expire_at,
                expired, locked, locked_at, locked_by_id, latest_revision_id,
                live_revision_id, title, text, button_text, button_url,
                target_url_id, image_id, image_layout, image_style
            )
            SELECT
                id, translation_key, locale_id, live, has_unpublished_changes,
                first_published_at, last_published_at, go_live_at, expire_at,
                expired, locked, locked_at, locked_by_id, latest_revision_id,
                live_revision_id, title, text, button_text, button_url,
                target_url_id, image_id, image_layout, image_style
            FROM site_settings_cta
        """)


def reverse_copy(apps, schema_editor):
    """
    Reverse - copy data back to site_settings
    """
    db_alias = schema_editor.connection.alias

    with schema_editor.connection.cursor() as cursor:
        # Delete existing data in site_settings_cta
        cursor.execute("DELETE FROM site_settings_cta")

        # Copy all data from home_cta to site_settings_cta
        cursor.execute("""
            INSERT INTO site_settings_cta (
                id, translation_key, locale_id, live, has_unpublished_changes,
                first_published_at, last_published_at, go_live_at, expire_at,
                expired, locked, locked_at, locked_by_id, latest_revision_id,
                live_revision_id, title, text, button_text, button_url,
                target_url_id, image_id, image_layout, image_style
            )
            SELECT
                id, translation_key, locale_id, live, has_unpublished_changes,
                first_published_at, last_published_at, go_live_at, expire_at,
                expired, locked, locked_at, locked_by_id, latest_revision_id,
                live_revision_id, title, text, button_text, button_url,
                target_url_id, image_id, image_layout, image_style
            FROM home_cta
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homepage_body_delete_homepagegalleryimage'),
        ('images', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Recreate the CTA model in home
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('title', models.CharField(help_text='The CTA title', max_length=255)),
                ('text', wagtail.fields.RichTextField(help_text='The main CTA text content')),
                ('button_text', models.CharField(blank=True, help_text='Button text', max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, help_text='Button URL', null=True)),
                ('image_layout', models.CharField(choices=[('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], default='background', help_text='How to display the image', max_length=20)),
                ('image_style', models.CharField(choices=[('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], default='fill', help_text='Style for left/right images (not used for background)', max_length=20)),
                ('image', models.ForeignKey(blank=True, help_text='Optional image for the CTA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('target_url', models.ForeignKey(blank=True, help_text='Optional: Make the entire CTA clickable by selecting a target page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
        # Copy the data
        migrations.RunPython(copy_cta_data_back, reverse_copy),
    ]
