# Generated by Django 5.2.9 on 2025-12-23 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_restore_cta_from_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='CTA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_cta', to='home.cta'),
        ),
    ]
