# Generated by Django 5.2.9 on 2025-12-23 23:54

from django.db import migrations


def rebuild_homepage_table(apps, schema_editor):
    """
    Rebuild the home_homepage table with correct foreign key to home_cta
    """
    with schema_editor.connection.cursor() as cursor:
        # Disable foreign key checks
        cursor.execute("PRAGMA foreign_keys=OFF")

        # Create new table with correct foreign key
        cursor.execute("""
            CREATE TABLE "home_homepage_new" (
                "page_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED,
                "body" text NULL CHECK ((JSON_VALID("body") OR "body" IS NULL)),
                "CTA_id" bigint NULL REFERENCES "home_cta" ("id") DEFERRABLE INITIALLY DEFERRED
            )
        """)

        # Copy data from old table
        cursor.execute("""
            INSERT INTO home_homepage_new (page_ptr_id, body, CTA_id)
            SELECT page_ptr_id, body, CTA_id FROM home_homepage
        """)

        # Drop old table
        cursor.execute("DROP TABLE home_homepage")

        # Rename new table
        cursor.execute("ALTER TABLE home_homepage_new RENAME TO home_homepage")

        # Recreate index
        cursor.execute('CREATE INDEX "home_homepage_CTA_id_08185a48" ON "home_homepage" ("CTA_id")')

        # Re-enable foreign key checks
        cursor.execute("PRAGMA foreign_keys=ON")


def reverse_rebuild(apps, schema_editor):
    """
    Reverse - rebuild with foreign key to site_settings_cta
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys=OFF")

        cursor.execute("""
            CREATE TABLE "home_homepage_new" (
                "page_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "wagtailcore_page" ("id") DEFERRABLE INITIALLY DEFERRED,
                "body" text NULL CHECK ((JSON_VALID("body") OR "body" IS NULL)),
                "CTA_id" bigint NULL REFERENCES "site_settings_cta" ("id") DEFERRABLE INITIALLY DEFERRED
            )
        """)

        cursor.execute("""
            INSERT INTO home_homepage_new (page_ptr_id, body, CTA_id)
            SELECT page_ptr_id, body, CTA_id FROM home_homepage
        """)

        cursor.execute("DROP TABLE home_homepage")
        cursor.execute("ALTER TABLE home_homepage_new RENAME TO home_homepage")
        cursor.execute('CREATE INDEX "home_homepage_CTA_id_08185a48" ON "home_homepage" ("CTA_id")')
        cursor.execute("PRAGMA foreign_keys=ON")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_update_homepage_cta_fk'),
    ]

    operations = [
        migrations.RunPython(rebuild_homepage_table, reverse_rebuild, atomic=False),
    ]
