# Generated by Django 5.2.9 on 2025-12-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rebuild_homepage_table'),
    ]

    operations = [
        # Rename the CTA model to Hero
        migrations.RenameModel(
            old_name='CTA',
            new_name='Hero',
        ),
        # Rename the HomePage.CTA field to hero
        migrations.RenameField(
            model_name='homepage',
            old_name='CTA',
            new_name='hero',
        ),
    ]
