# Generated by Django 5.2.9 on 2025-12-24 20:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_cta_to_hero'),
        ('images', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Optional image for the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_layout',
            field=models.CharField(choices=[('background', 'Background - Image fills entire hero as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], default='background', help_text='How to display the image', max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='target_url',
            field=models.ForeignKey(blank=True, help_text='Optional: Make the entire hero clickable by selecting a target page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='text',
            field=wagtail.fields.RichTextField(help_text='The main hero text content'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(help_text='The hero title', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('cta_text', 4), ('six_philosophies', 5), ('programs', 8), ('text', 9), ('rich_text', 10), ('image', 11), ('page', 12), ('recent_news', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('headline', 0), ('text', 1), ('page', 2), ('button_text', 3)]], {}), 5: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Our Programs', 'help_text': 'Main heading for this programs section', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7)]], {}), 9: ('blocks.blocks.TextBlock', (), {}), 10: ('blocks.blocks.RichTextBlock', (), {}), 11: ('blocks.blocks.ImageBlock', (), {}), 12: ('blocks.blocks.CustomPageChooserBlock', (), {'group': 'Standalone Blocks', 'page_type': ['news.NewsItem'], 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main heading for this news section', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'help_text': 'Number of recent news items to display', 'max_value': 10, 'min_value': 1, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter news items by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 7), ('num_items', 14), ('filter_by_tag', 15)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_hero', to='home.hero'),
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together={('translation_key', 'locale')},
        ),
    ]
