# Generated by Django 5.1.8 on 2025-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Footer Text')),
            ],
            options={
                'verbose_name': 'Generic Footer Text',
            },
        ),
    ]
