# Generated by Django 5.2.9 on 2026-01-09 01:06

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('title', models.CharField(help_text='The banner title (will be displayed in bold)', max_length=255)),
                ('content', wagtail.fields.RichTextField(help_text='The banner content/message')),
                ('color', models.CharField(choices=[('bg-blue-800/90', 'Blue (Default)'), ('bg-green-800/90', 'Green'), ('bg-red-800/90', 'Red'), ('bg-yellow-800/90', 'Yellow'), ('bg-purple-800/90', 'Purple'), ('bg-gray-800/90', 'Gray')], default='bg-blue-800/90', help_text='Banner background color', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Only one banner should be active at a time')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-is_active', '-pk'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
    ]
