# Generated by Django 5.2.9 on 2026-01-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='color',
            field=models.CharField(choices=[('banner-bg-blue', 'Blue (Default)'), ('banner-bg-green', 'Green'), ('banner-bg-red', 'Red'), ('banner-bg-yellow', 'Yellow'), ('banner-bg-purple', 'Purple'), ('banner-bg-gray', 'Gray')], default='banner-bg-blue', help_text='Banner background color', max_length=50),
        ),
    ]
