# Generated by Django 5.2.7 on 2025-11-18 00:19

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_categories_forward(apps, schema_editor):
    """
    Migrate existing FAQ category strings to FAQCategory objects.
    """
    FAQ = apps.get_model('site_settings', 'FAQ')
    FAQCategory = apps.get_model('site_settings', 'FAQCategory')

    # Get all FAQs with their temp category values
    faqs = FAQ.objects.all()
    categories = set()
    for faq in faqs:
        if faq.category_temp:
            categories.add(faq.category_temp)

    # Create FAQCategory objects for each unique category
    category_map = {}
    for idx, category_name in enumerate(sorted(categories)):
        if category_name:  # Skip empty strings
            slug = slugify(category_name)
            # Handle potential slug conflicts
            original_slug = slug
            counter = 1
            while FAQCategory.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1

            category_obj = FAQCategory.objects.create(
                name=category_name,
                slug=slug,
                order=idx * 10  # Space out order values
            )
            category_map[category_name] = category_obj

    # Update FAQs to link to the new category objects
    for faq in faqs:
        if faq.category_temp and faq.category_temp in category_map:
            faq.category = category_map[faq.category_temp]
            faq.save()


def migrate_categories_backward(apps, schema_editor):
    """
    Migrate FAQCategory objects back to category strings.
    """
    FAQ = apps.get_model('site_settings', 'FAQ')

    # Store category names back into the category field
    for faq in FAQ.objects.all():
        if faq.category:
            faq.category = faq.category.name


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_faq_faqtags_faq_tags'),
    ]

    operations = [
        # Step 1: Create FAQCategory model
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Registration', 'Programs', 'General')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('order', models.IntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),

        # Step 2: Add a temporary field to store the old category value
        migrations.AddField(
            model_name='faq',
            name='category_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        # Step 3: Copy existing category data to temp field
        migrations.RunSQL(
            "UPDATE site_settings_faq SET category_temp = category;",
            reverse_sql="UPDATE site_settings_faq SET category = category_temp;",
        ),

        # Step 4: Remove the old category field
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),

        # Step 5: Add the new ForeignKey category field
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category for grouping FAQs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='site_settings.faqcategory'),
        ),

        # Step 6: Migrate the data
        migrations.RunPython(migrate_categories_forward, reverse_code=migrate_categories_backward),

        # Step 7: Remove the temporary field
        migrations.RemoveField(
            model_name='faq',
            name='category_temp',
        ),
    ]
