# Generated by Django 5.2.9 on 2025-12-23 23:41

from django.db import migrations


def drop_cta_table(apps, schema_editor):
    """
    Drop the site_settings_cta table
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS site_settings_cta")


def recreate_cta_table(apps, schema_editor):
    """
    Reverse - recreate the table (this is a placeholder, actual structure would need to be defined)
    """
    # This is intentionally left simple since reversing is unlikely
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_faqcategory_alter_faq_category'),
        ('home', '0024_update_homepage_cta_fk'),
    ]

    operations = [
        migrations.RunPython(drop_cta_table, recreate_cta_table, atomic=False),
    ]
