# Generated by Django 6.0.2 on 2026-03-06 00:35

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('title', models.CharField(help_text='Internal title for identifying this CTA in the admin', max_length=255)),
                ('heading', models.CharField(help_text='Heading displayed in the CTA', max_length=255)),
                ('text', wagtail.fields.RichTextField(help_text='Main body text for the CTA')),
                ('button_text', models.CharField(blank=True, help_text="Button label (leave blank to use the linked page's title)", max_length=100)),
                ('button_url', models.URLField(blank=True, help_text='External URL for the button (used only if no page is selected)')),
                ('layout', models.CharField(choices=[('text_left', 'Text Left, Image Right'), ('image_left', 'Image Left, Text Right'), ('centered', 'Text Centered (No Image)')], default='centered', help_text='How to arrange the text and optional image', max_length=20)),
                ('background', models.CharField(blank=True, choices=[('', 'Default (Inherit)'), ('cta-bg-light', 'Light Gray'), ('cta-bg-primary', 'Primary Tint'), ('cta-bg-secondary', 'Secondary Tint'), ('cta-bg-blue', 'Blue Gradient'), ('cta-bg-green', 'Green Gradient'), ('cta-bg-purple', 'Purple Gradient'), ('cta-bg-warm', 'Warm Gradient'), ('cta-bg-dark', 'Dark')], default='', help_text='Background colour or gradient for this CTA', max_length=30)),
                ('button_page', models.ForeignKey(blank=True, help_text='Internal page for the button to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('image', models.ForeignKey(blank=True, help_text="Optional image (not used for 'Text Centered' layout)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
            ],
            options={
                'verbose_name': 'CTA',
                'verbose_name_plural': 'CTAs',
                'ordering': ['title'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
    ]
