# Generated by Django 5.1.8 on 2025-04-28 21:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('body', wagtail.fields.StreamField([('info', 0), ('text', 1), ('image', 2), ('call_to_action_1', 6), ('faq', 7)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.ImageBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('page', 4), ('button_text', 5)]], {}), 7: ('blocks.blocks.FaqListBlock', (), {})}, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
