# Generated by Django 5.2.9 on 2026-01-05 23:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('six', 0), ('text', 1), ('richtext', 2), ('image', 3), ('call_to_action_1', 11)], blank=True, block_lookup={0: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.RichTextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'The main CTA text content', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page for the button to link to', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text (defaults to page title if empty)', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional: Make the entire CTA clickable by selecting a target page', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image for the CTA', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], 'help_text': 'How to display the image', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], 'help_text': 'Style for left/right images (not used for background)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6), ('target_url', 7), ('image', 8), ('image_layout', 9), ('image_style', 10)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', wagtail.fields.RichTextField()),
                ('ages', models.CharField(blank=True, max_length=200)),
                ('tryouts', wagtail.fields.RichTextField(blank=True)),
                ('equipment', wagtail.fields.RichTextField(blank=True)),
                ('schedule', wagtail.fields.RichTextField(blank=True)),
                ('location', wagtail.fields.RichTextField(blank=True, max_length=200)),
                ('registration', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('six', 0), ('text', 1), ('richtext', 2), ('image', 3), ('call_to_action_1', 11), ('faq_block', 18)], blank=True, block_lookup={0: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.RichTextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'The main CTA text content', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page for the button to link to', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text (defaults to page title if empty)', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional: Make the entire CTA clickable by selecting a target page', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional image for the CTA', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('background', 'Background - Image fills entire CTA as background'), ('left', 'Left - Image on left, text on right'), ('right', 'Right - Image on right, text on left')], 'help_text': 'How to display the image', 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fill', 'Fill - Image fills entire section'), ('framed', 'Framed - Image with rounded edges and padding')], 'help_text': 'Style for left/right images (not used for background)', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6), ('target_url', 7), ('image', 8), ('image_layout', 9), ('image_style', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'help_text': 'Main heading for this FAQ section', 'max_length': 100, 'required': True}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description text', 'max_length': 200, 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter FAQs by tag (leave blank to show all)', 'max_length': 50, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional: filter FAQs by category (leave blank to show all)', 'max_length': 100, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'help_text': 'Number of FAQs to display (0 = show all matching items)', 'max_value': 50, 'min_value': 0, 'required': True}), 17: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display category labels for each FAQ', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('filter_by_tag', 14), ('filter_by_category', 15), ('num_items', 16), ('show_categories', 17)]], {})}, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
