# Generated by Django 5.1.8 on 2025-04-29 14:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AlterField(
            model_name='program',
            name='body',
            field=wagtail.fields.StreamField([('info', 0), ('text', 1), ('richtext', 2), ('image', 3), ('call_to_action_1', 7), ('faq', 8)], blank=True, block_lookup={0: ('blocks.blocks.InfoBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.RichTextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6)]], {}), 8: ('blocks.blocks.FaqListBlock', (), {})}, null=True),
        ),
    ]
