# Generated by Django 5.1.8 on 2025-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_logo_alter_program_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
