# Generated by Django 5.1.8 on 2025-04-30 00:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='body',
            field=wagtail.fields.StreamField([('six', 0), ('text', 1), ('richtext', 2), ('image', 3), ('call_to_action_1', 7), ('faq', 8)], blank=True, block_lookup={0: ('blocks.blocks.SixPhilosophiesBlock', (), {}), 1: ('blocks.blocks.TextBlock', (), {}), 2: ('blocks.blocks.RichTextBlock', (), {}), 3: ('blocks.blocks.ImageBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6)]], {}), 8: ('blocks.blocks.FaqListBlock', (), {})}, null=True),
        ),
    ]
