# Generated by Django 5.2 on 2025-05-07 05:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='equipment',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='location',
            field=wagtail.fields.RichTextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='registration',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='schedule',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tryouts',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
