# Generated by Django 5.2.7 on 2025-10-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_ages_program_equipment_program_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programindex',
            name='body',
        ),
    ]
