# Generated by Django 5.2.7 on 2025-10-29 18:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programindex_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='programindex',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
