# Generated by Django 5.2.7 on 2025-10-30 17:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_programindex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
